version: '3.8'
services:
    mysql:
        image: mysql:8.0
        container_name: benwork-mysql-dev
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'nghia1234'
            MYSQL_DATABASE: 'benwork_db_dev'
            MYSQL_USER: 'nghia'
            MYSQL_PASSWORD: 'nghia1234'
        command:
            [
                mysqld,
                --authentication-policy=mysql_native_password,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
                --innodb_monitor_enable=all,
                --max-connections=1001,
            ]
        volumes:
            - mysql-data:/data/db

    redis:
        image: redis:7
        container_name: benwork-redis-dev
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

volumes:
    mysql-data:
    redis-data:
